# Generated by Django 4.0.5 on 2022-06-19 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighborhood',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neighborhood'),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Business name', max_length=30)),
                ('business_email', models.EmailField(default='Business email', max_length=30)),
                ('business_phone', models.CharField(default='Business phone', max_length=30)),
                ('business_location', models.CharField(default='Business location', max_length=30)),
                ('business_description', models.TextField(default='Business description', max_length=600)),
                ('business_image', models.ImageField(upload_to='business_pics')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighborhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
